GET http://localhost:5000/api/notes

###
# Register user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Test User",
    "email": "testuser@email.com",
    "password": "password123"
}

###
# Login user (dapatkan accessToken)
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "testuser@email.com",
    "password": "password123"
}

###
# Create note (ganti {token} dengan accessToken hasil login)
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJUZXN0IFVzZXIiLCJlbWFpbCI6InRlc3R1c2VyQGVtYWlsLmNvbSIsImlhdCI6MTc0ODI1MzMyMiwiZXhwIjoxNzQ4MjU2OTIyfQ.-uEnDAHQj3OWhp0vKVxUgrO20GAFIza_D3NGQ9Yxn8k

{
    "title": "Note Pertama Yeyy",
    "content": "Isi apa ajalah yang penting Notenya berhasil"
}

###
# Update
PATCH http://localhost:5000/api/notes/1
Content-Type: application/json
Authorization: Bearer {token}

{
    "title": "Berhasil juga yeay",
    "content": "Dah mummet ewww"
}

###
# Delete
DELETE http://localhost:5000/api/notes/2
Authorization: Bearer {token}

###
POST http://localhost:5000/api/notes
Content-Type: application/json
Authorization: Bearer {token}

{
    "title" : "Migrasi GCP",
    "content" : "Mencoba melakukan migrasi ke Google Cloud Platform"
}